main: club.spfmc.simplewarps.SimpleWarps
name: SimpleWarps
version: 1.0
author: SirOswaldo
website: https://www.kayteam.org
softdepend:
  - PlaceholderAPI
commands:
  SimpleWarps:
    description: Manage this plugin.
  ManageWarps:
    description: Manage warps
  CreateWarp:
    description: Create one warp
  DeleteWarp:
    description: Delete one warp
  Warp:
    description: Teleport to specific warp
  Warps:
    description: Open Warps GUI
  EditWarp:
    description: Edit Warp
permissions:
  simple.admin.warps:
    description: Manage this plugin.