inventory:
  warps:
    title: "Warps"
  manageWarps:
    title: "Manage Warp Menu"
    rows: 1
    items:
      warp:
        material: "ENDER_PEARL"
        name: "&6%warp_name%"
        lore:
          - "&7"
          - "&3GUI&b:"
          - "  &6Enabled&e: %warp_gui_enabled%"
          - "  &6Position&e: &f%warp_gui_position%"
          - "&7"
          - "&3CORDS&b:"
          - "  &6World&e: &f%warp_world%"
          - "  &6X&e: &f%warp_x%"
          - "  &6Y&e: &f%warp_y%"
          - "  &6Z&e: &f%warp_z%"
          - "  &6Yaw&e: &f%warp_yaw%"
          - "  &6Pitch&e: &f%warp_pitch%"
          - "&7"
          - "&7Left Click to Teleport"
          - "&7Right Click to Edit"
          - "&7Shift Right Click to Delete"
      panel:
        material: "STAINED_GLASS_PANE"
        data: 1
      information:
        material: "PAPER"
        name: "&6Information"
        lore:
          - "&7"
          - "&6Amount&e: &f%warps_amount%"
      previous:
        material: "ARROW"
        name: "&cPrevious Page"
      close:
        material: "BARRIER"
        name: "&cClose Menu"
      next:
        material: "ARROW"
        name: "&cNext Page"

